### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by CactusKing101** [CactusKing101/Eggy-Bot#1]
Sending a pissy chain
Meaning the bot spams the same image over and over for no reason.

**Comment by CactusKing101** [comment]
![unown](https://user-images.githubusercontent.com/44009236/110579209-4b819c80-8134-11eb-9a3f-0ec89094c7e7.png)
no reason for the spam 😳

**Comment by IndianBoy6** [comment]
This actually occurred because a user spammed it many times then deleted the message, not because of a bug. Looking into a cooldown right now.
